AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Encode provided string into pixelated square

Resources:
  EncodeApi:
    Type: AWS::Serverless::HttpApi
    Properties: {}

  EncodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1024
      Timeout: 30
      Architectures:
        - x86_64
      Events:
        HttpInvoke:
          Type: HttpApi
          Properties:
            ApiId: !Ref EncodeApi
            Path: /generate
            Method: POST
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest

Outputs:
  InvokeURL:
    Description: "API endpoint URL for the function"
    Value:
      Fn::Sub: "https://${EncodeApi}.execute-api.${AWS::Region}.amazonaws.com/generate"
