AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  A simple AWS SAM template that deploys a Lambda function with an HTTP API endpoint returning "Hello World".

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.app.lambda_handler
      Runtime: python3.13
      Events:
        HelloWorldAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  HelloWorldApiUrl:
    Description: "URL for the Hello World API endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
